name: vo
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - numpy>=1.24.0
    - matplotlib>=3.7.0
    - pyyaml>=6.0
    - pip
    - pip:
          - opencv-python>=4.8.0
          - opencv-contrib-python>=4.8.0
          - pytest>=7.4.0
          - pytest-cov>=4.1.0
